name: Save and plot traffic data

on:
  push:
    paths:
    - 'traffic/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt
          
      - name: Execute notebook
        run: jupyter nbconvert --execute gget_traffic.ipynb
      
      - name: Commit and push new data
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git checkout traffic
          git status
          git add traffic_archive/* plots/*
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
      - name: Clean up
        run: rm gget_traffic.html && yes | rm -r gget
